[package]
name = "blitzkrieg"
version = "0.1.0-dev"
edition = "2021"

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy", features = ["wayland"] }
clap = { version = "4.5", features = ["derive"] }
derive_more = { version = "1.0.0", features = ["constructor"] }